"use strict";

function escapeHtml(value) {
  return String(value == null ? "" : value).replace(/[&<>"']/g, function (char) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char];
  });
}

function safeJson(value) {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026");
}

module.exports = function renderAppointmentPanel(res, options) {
  const business = options.business;
  const auth = options.auth || {};
  const dataPath = options.dataPath;
  const integration = options.integration || {};
  res.status(200).setHeader("content-type", "text/html; charset=utf-8");
  res.send(`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Citas · ${escapeHtml(business.brand_name)}</title><style>
:root{--navy:#071832;--blue:#12a8f4;--bg:#f5f8fc;--card:#fff;--line:#dce5f1;--text:#081634;--muted:#6f7f98;--green:#11875d;--amber:#bd7412;--red:#b53d46}*{box-sizing:border-box}body{margin:0;font:14px/1.45 Inter,system-ui,sans-serif;background:var(--bg);color:var(--text)}header{background:var(--navy);color:#fff;padding:22px 5vw;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{display:flex;align-items:center;gap:13px}.mark{width:44px;height:44px;border-radius:13px;background:var(--blue);display:grid;place-items:center;font-weight:900}.brand h1{font-size:18px;margin:0}.brand p{margin:3px 0 0;color:#bad0ea}.user{color:#d9e7f7}main{width:min(1180px,92vw);margin:28px auto 60px}.hero,.card{background:var(--card);border:1px solid var(--line);border-radius:20px;box-shadow:0 10px 28px rgba(8,22,52,.06)}.hero{padding:26px;display:flex;justify-content:space-between;gap:24px;align-items:center}.hero h2{font-size:28px;margin:5px 0}.hero p{color:var(--muted);margin:0}.badge{display:inline-block;padding:7px 11px;border-radius:999px;background:#e7f8f0;color:var(--green);font-weight:800;font-size:12px}.sync{text-align:right}.sync strong{display:block}.sync span{color:var(--muted);font-size:12px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin:18px 0}.metric{padding:20px}.metric span{color:var(--muted);font-weight:700}.metric strong{display:block;font-size:32px;margin-top:12px}.grid{display:grid;grid-template-columns:2fr 1fr;gap:18px}.card h3{margin:0}.cardHead{display:flex;justify-content:space-between;align-items:center;padding:20px;border-bottom:1px solid var(--line)}.tableWrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px 18px;border-bottom:1px solid #edf1f6;white-space:nowrap}th{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.05em}.status{padding:6px 9px;border-radius:999px;background:#eef4fb;font-weight:800;font-size:11px}.status.booked,.status.rescheduled{background:#e7f8f0;color:var(--green)}.status.requested{background:#fff3de;color:var(--amber)}.status.cancelled,.status.failed{background:#fdecee;color:var(--red)}.empty{padding:34px;text-align:center;color:var(--muted)}.checklist{padding:18px}.check{display:flex;gap:11px;padding:12px 0;border-bottom:1px solid #edf1f6}.dot{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;background:#e7f8f0;color:var(--green);font-weight:900}.dot.pending{background:#fff3de;color:var(--amber)}.check strong{display:block}.check small{color:var(--muted)}@media(max-width:850px){header,.hero{align-items:flex-start;flex-direction:column}.sync{text-align:left}.metrics{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}}@media(max-width:520px){.metrics{grid-template-columns:1fr}.hero h2{font-size:23px}}
</style></head><body><header><div class="brand"><div class="mark">NX</div><div><h1>Nextfor IA</h1><p>Cliente #${escapeHtml(business.customer_number)} · ${escapeHtml(business.brand_name)}</p></div></div><div class="user">${escapeHtml(auth.name || auth.username || "Panel")}</div></header><main><section class="hero"><div><span class="badge">Piloto activo</span><h2>Agendamiento de citas</h2><p>Luciana + Google Calendar + Nextfor IA, en un solo lugar.</p></div><div class="sync"><strong id="syncState">Cargando citas…</strong><span id="syncDetail">Sincronización segura desde ElevenLabs</span></div></section><section class="metrics"><article class="card metric"><span>Citas solicitadas</span><strong id="mRequested">—</strong></article><article class="card metric"><span>Citas confirmadas</span><strong id="mBooked">—</strong></article><article class="card metric"><span>Pendientes</span><strong id="mPending">—</strong></article><article class="card metric"><span>Canceladas</span><strong id="mCancelled">—</strong></article></section><section class="grid"><article class="card"><div class="cardHead"><h3>Próximas citas</h3><span id="appointmentCount">0 registros</span></div><div class="tableWrap"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Motivo</th><th>Estado</th></tr></thead><tbody id="appointmentRows"></tbody></table><div class="empty" id="emptyState">Todavía no hay citas recibidas desde ElevenLabs.</div></div></article><aside class="card"><div class="cardHead"><h3>Integraciones</h3></div><div class="checklist"><div class="check"><span class="dot">✓</span><div><strong>ElevenLabs</strong><small>Agente de voz configurado</small></div></div><div class="check"><span class="dot">✓</span><div><strong>Google Calendar</strong><small>Proveedor inicial de agenda</small></div></div><div class="check"><span class="dot ${integration.webhook_ready ? "" : "pending"}">${integration.webhook_ready ? "✓" : "!"}</span><div><strong>Nextfor IA</strong><small>${integration.webhook_ready ? "Webhook listo" : "Falta activar secreto del webhook"}</small></div></div></div></aside></section></main><script>
var DATA_PATH=${safeJson(dataPath)};function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}function setText(id,v){var e=document.getElementById(id);if(e)e.textContent=v}function dateLabel(v){if(!v)return"Por confirmar";var d=new Date(v);return isNaN(d)?"Por confirmar":d.toLocaleString("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Bogota"})}function statusLabel(v){return{booked:"Confirmada",requested:"Solicitada",failed:"Fallida",cancelled:"Cancelada",rescheduled:"Reagendada",not_requested:"Sin solicitud"}[v]||v}fetch(DATA_PATH,{headers:{accept:"application/json"}}).then(function(r){return r.json().then(function(b){if(!r.ok)throw new Error(b.error||"HTTP "+r.status);return b})}).then(function(data){var m=data.metrics||{},rows=data.upcoming||[];setText("mRequested",m.requested||0);setText("mBooked",m.booked||0);setText("mPending",m.pending||0);setText("mCancelled",m.cancelled||0);setText("syncState","Sincronización activa");setText("syncDetail",data.source==="supabase"?"Datos persistentes en Nextfor":"Modo piloto en memoria");setText("appointmentCount",rows.length+" registro"+(rows.length===1?"":"s"));var body=document.getElementById("appointmentRows"),empty=document.getElementById("emptyState");if(empty)empty.style.display=rows.length?"none":"block";if(body)body.innerHTML=rows.map(function(row){return"<tr><td>"+esc(dateLabel(row.starts_at))+"</td><td><strong>"+esc(row.customer_name||"Cliente por confirmar")+"</strong><br><small>"+esc(row.customer_phone||row.customer_email||"")+"</small></td><td>"+esc(row.consultation_reason||"Sin detalle")+"</td><td><span class=\\\"status "+esc(row.status)+"\\\">"+esc(statusLabel(row.status))+"</span></td></tr>"}).join("")}).catch(function(error){setText("syncState","Revisar conexión");setText("syncDetail",error.message)});
</script></body></html>`);
};
