"use strict";

const { safeInlineJson } = require("./security");

function renderCustomerLogin(res, options) {
  options = options || {};
  const target = safeInlineJson(options.targetPath || "/admin/panel?tab=summary");
  res.status(200).setHeader("content-type", "text/html; charset=utf-8");
  res.send(`<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ingresar al Panel de Control · Nextfor IA</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Sora:wght@600;700;800&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap');
:root{--navy:#071832;--navy2:#0E2148;--cyan:#00A0F0;--cyan2:#25BFFF;--line:#DFE6F0;--muted:#647289;--bg:#F4F7FB;--body:"Plus Jakarta Sans","Avenir Next",sans-serif;--display:"Sora","Avenir Next",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:var(--bg);font-family:var(--body);color:var(--navy);display:grid;place-items:center;padding:28px}.shell{width:min(960px,100%);min-height:590px;background:#fff;border:1px solid var(--line);border-radius:26px;overflow:hidden;display:grid;grid-template-columns:390px 1fr;box-shadow:0 32px 72px -35px rgba(7,24,50,.38)}.intro{background:linear-gradient(155deg,var(--navy2),#060F22);color:#fff;padding:42px 38px;display:flex;flex-direction:column;justify-content:space-between}.brand{display:flex;align-items:center;gap:12px}.mark{width:50px;height:50px;border-radius:15px;background:linear-gradient(145deg,var(--cyan2),var(--cyan));display:grid;place-items:center;font:800 15px var(--display)}.brand strong{display:block;font:700 17px var(--display)}.brand span{font-size:12px;color:rgba(255,255,255,.62)}.copy small{display:block;color:#63CAF8;font-weight:800;letter-spacing:.12em;margin-bottom:14px}.copy h1{font:700 30px/1.18 var(--display);letter-spacing:-.035em;margin:0 0 16px}.copy p{color:rgba(255,255,255,.7);font-size:14px;line-height:1.65;margin:0}.safe{font-size:12px;color:rgba(255,255,255,.66)}.safe:before{content:"";display:inline-block;width:8px;height:8px;border-radius:50%;background:#20C486;margin-right:9px}.formPanel{padding:56px;display:grid;place-items:center}.form{width:min(100%,420px)}.eyebrow{font-size:11px;color:#0788C7;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.form h2{font:700 30px/1.14 var(--display);letter-spacing:-.035em;margin:11px 0}.lead{font-size:14px;line-height:1.6;color:var(--muted);margin:0 0 27px}.field{margin-top:18px}label{display:block;font-size:13px;font-weight:800;margin-bottom:8px}.inputWrap{position:relative}input{width:100%;height:52px;border:1.5px solid #C6D1E0;border-radius:12px;padding:0 15px;font:500 15px var(--body);color:var(--navy);outline:0}input:focus{border-color:var(--cyan);box-shadow:0 0 0 4px rgba(0,160,240,.13)}input.password{padding-right:96px}.show{position:absolute;right:8px;top:8px;height:36px;border:0;border-radius:9px;background:#EDF1F7;color:#52617B;font:700 12px var(--body);padding:0 13px;cursor:pointer}.primary{width:100%;min-height:54px;border:0;border-radius:13px;background:linear-gradient(135deg,var(--cyan2),var(--cyan));color:#fff;font:800 15px var(--display);margin-top:24px;cursor:pointer}.primary:disabled{opacity:.5;cursor:not-allowed}.error{min-height:20px;color:#B94723;font-size:12px;text-align:center;margin-top:10px}.help{font-size:12.5px;color:var(--muted);text-align:center;line-height:1.55;margin:18px 0 0}.help strong{color:var(--navy)}
@media(max-width:760px){body{display:block;padding:0}.shell{min-height:100vh;border:0;border-radius:0;display:flex;flex-direction:column}.intro{margin:14px 14px 0;padding:20px;border-radius:22px;min-height:178px}.copy small{font-size:9px;margin:18px 0 7px}.copy h1{font-size:21px;margin:0}.copy p,.safe{display:none}.mark{width:44px;height:44px}.formPanel{display:block;padding:30px 24px}.form{max-width:none}.eyebrow{display:none}.form h2{font-size:25px}.lead{font-size:13.5px;margin-bottom:22px}}
</style></head><body><main class="shell"><section class="intro" aria-label="Nextfor IA"><div class="brand"><div class="mark">NIA</div><div><strong>Nextfor IA</strong><span>Panel de Control</span></div></div><div class="copy"><small>TU OPERACIÓN, EN UN SOLO LUGAR</small><h1>Bienvenido de vuelta.</h1><p>Consulta resultados, conversaciones y tareas de tu asistente con acceso exclusivo a tu empresa.</p></div><div class="safe">Acceso privado y separado por empresa</div></section><section class="formPanel"><form class="form" id="loginForm"><div class="eyebrow">Panel de Control</div><h2>Ingresa a tu panel</h2><p class="lead">Usa tu correo y contraseña. Si todavía no tienes cuenta, puedes crearla y empezar el setup.</p><div class="field"><label for="email">Correo electrónico</label><input id="email" type="email" autocomplete="email" inputmode="email" autocapitalize="off" spellcheck="false" placeholder="tu@empresa.com" required autofocus></div><div class="field"><label for="password">Contraseña</label><div class="inputWrap"><input class="password" id="password" type="password" autocomplete="current-password" required><button class="show" id="showPassword" type="button">Mostrar</button></div></div><button class="primary" id="submitButton" type="submit" disabled>Entrar al panel</button><div class="error" id="error" role="alert"></div><p class="help">¿No tienes acceso? <a href="/admin/create-account"><strong>Crea tu cuenta</strong></a></p></form></section></main>
<script>
var target=${target},form=document.getElementById("loginForm"),email=document.getElementById("email"),password=document.getElementById("password"),button=document.getElementById("submitButton"),error=document.getElementById("error");
function clearPanelBrowserState(){try{["rav_dashboard_key","rav_dashboard_tab","rav_logo","nextfor-integration-result"].forEach(function(key){localStorage.removeItem(key);});}catch(_){}try{["nextforia_tenant_id","tenant_id","rav_tenant_id"].forEach(function(key){sessionStorage.removeItem(key);});}catch(_){}}
function ready(){button.disabled=!/^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email.value.trim())||!password.value;}
email.addEventListener("input",ready);password.addEventListener("input",ready);document.getElementById("showPassword").addEventListener("click",function(){var show=password.type==="password";password.type=show?"text":"password";this.textContent=show?"Ocultar":"Mostrar";password.focus();});
form.addEventListener("submit",function(event){event.preventDefault();if(button.disabled)return;clearPanelBrowserState();error.textContent="";button.disabled=true;button.textContent="Entrando…";fetch("/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:email.value.trim(),password:password.value})}).then(function(response){return response.json().then(function(body){if(!response.ok)throw new Error(body.error||"invalid_credentials");return body;});}).then(function(body){clearPanelBrowserState();location.href=body.redirect||target;}).catch(function(){error.textContent="Correo o contraseña incorrectos.";button.textContent="Entrar al panel";ready();});});
</script></body></html>`);
}

module.exports = renderCustomerLogin;
