begin;

create extension if not exists pgcrypto;

create table if not exists public.bot_ops_events (
  seq bigint generated by default as identity primary key,
  event_id text not null unique,
  tenant_id text not null,
  bot_id text not null check (bot_id in ('customer_service', 'appointments', 'platform')),
  channel text not null,
  event_type text not null,
  conversation_key text,
  source_id text,
  occurred_at timestamptz not null,
  payload_ciphertext text not null,
  created_at timestamptz not null default now()
);

create index if not exists bot_ops_events_incremental_idx
  on public.bot_ops_events (seq, occurred_at);
create index if not exists bot_ops_events_tenant_idx
  on public.bot_ops_events (tenant_id, occurred_at desc);

create table if not exists public.bot_ops_runs (
  id uuid primary key default gen_random_uuid(),
  review_type text not null check (review_type in ('daily', 'weekly')),
  schedule_key text not null,
  status text not null default 'running' check (status in ('running', 'completed', 'failed')),
  owner text,
  lease_until timestamptz,
  cursor_start bigint not null default 0,
  cursor_end bigint not null default 0,
  overall_status text check (overall_status is null or overall_status in ('healthy', 'attention', 'critical')),
  summary jsonb not null default '{}'::jsonb,
  counts jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (review_type, schedule_key)
);

create index if not exists bot_ops_runs_latest_idx
  on public.bot_ops_runs (review_type, status, completed_at desc);

create table if not exists public.bot_ops_state (
  review_type text primary key check (review_type in ('daily', 'weekly')),
  last_event_seq bigint not null default 0,
  last_run_id uuid references public.bot_ops_runs(id),
  last_completed_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.bot_ops_state (review_type) values ('daily'), ('weekly')
on conflict (review_type) do nothing;

create table if not exists public.bot_ops_findings (
  id uuid primary key default gen_random_uuid(),
  dedupe_key text not null unique,
  run_id uuid references public.bot_ops_runs(id),
  tenant_id text not null,
  bot_id text not null check (bot_id in ('customer_service', 'appointments', 'platform')),
  channel text not null,
  category text not null,
  severity text not null check (severity in ('opportunity', 'attention', 'critical')),
  status text not null check (status in ('open', 'approval_pending', 'resolved')),
  title text not null,
  detail text not null,
  recommendation text not null,
  requires_approval boolean not null default false,
  conversation_key text,
  source_event_id text,
  evidence jsonb not null default '{}'::jsonb,
  safe_action jsonb,
  first_seen_at timestamptz not null,
  last_seen_at timestamptz not null,
  resolved_at timestamptz,
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bot_ops_findings_open_idx
  on public.bot_ops_findings (status, severity, last_seen_at desc);
create index if not exists bot_ops_findings_tenant_idx
  on public.bot_ops_findings (tenant_id, bot_id, channel, last_seen_at desc);
create index if not exists bot_ops_findings_handoff_idx
  on public.bot_ops_findings (tenant_id, conversation_key, category, status);

create table if not exists public.bot_ops_finding_occurrences (
  dedupe_key text not null references public.bot_ops_findings(dedupe_key) on delete cascade,
  source_event_id text not null,
  run_id uuid references public.bot_ops_runs(id),
  occurred_at timestamptz not null,
  primary key (dedupe_key, source_event_id)
);

alter table public.bot_ops_events enable row level security;
alter table public.bot_ops_events force row level security;
alter table public.bot_ops_runs enable row level security;
alter table public.bot_ops_runs force row level security;
alter table public.bot_ops_state enable row level security;
alter table public.bot_ops_state force row level security;
alter table public.bot_ops_findings enable row level security;
alter table public.bot_ops_findings force row level security;
alter table public.bot_ops_finding_occurrences enable row level security;
alter table public.bot_ops_finding_occurrences force row level security;

drop policy if exists bot_ops_events_service_role on public.bot_ops_events;
create policy bot_ops_events_service_role on public.bot_ops_events
  for all to service_role using (true) with check (true);
drop policy if exists bot_ops_runs_service_role on public.bot_ops_runs;
create policy bot_ops_runs_service_role on public.bot_ops_runs
  for all to service_role using (true) with check (true);
drop policy if exists bot_ops_state_service_role on public.bot_ops_state;
create policy bot_ops_state_service_role on public.bot_ops_state
  for all to service_role using (true) with check (true);
drop policy if exists bot_ops_findings_service_role on public.bot_ops_findings;
create policy bot_ops_findings_service_role on public.bot_ops_findings
  for all to service_role using (true) with check (true);
drop policy if exists bot_ops_finding_occurrences_service_role on public.bot_ops_finding_occurrences;
create policy bot_ops_finding_occurrences_service_role on public.bot_ops_finding_occurrences
  for all to service_role using (true) with check (true);

revoke all on public.bot_ops_events from anon, authenticated;
revoke all on public.bot_ops_runs from anon, authenticated;
revoke all on public.bot_ops_state from anon, authenticated;
revoke all on public.bot_ops_findings from anon, authenticated;
revoke all on public.bot_ops_finding_occurrences from anon, authenticated;
grant select, insert, update, delete on public.bot_ops_events to service_role;
grant select, insert, update, delete on public.bot_ops_runs to service_role;
grant select, insert, update, delete on public.bot_ops_state to service_role;
grant select, insert, update, delete on public.bot_ops_findings to service_role;
grant select, insert, update, delete on public.bot_ops_finding_occurrences to service_role;
grant usage, select on sequence public.bot_ops_events_seq_seq to service_role;

create or replace function public.bot_ops_storage_ready_v1()
returns boolean
language sql
security definer
set search_path = public
as $$
  select to_regclass('public.bot_ops_events') is not null
    and to_regclass('public.bot_ops_runs') is not null
    and to_regclass('public.bot_ops_state') is not null
    and to_regclass('public.bot_ops_findings') is not null
    and to_regclass('public.bot_ops_finding_occurrences') is not null;
$$;

create or replace function public.claim_bot_ops_review_v1(
  p_review_type text,
  p_schedule_key text,
  p_owner text,
  p_lease_seconds integer default 900
)
returns setof public.bot_ops_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_state public.bot_ops_state%rowtype;
  v_run public.bot_ops_runs%rowtype;
  v_now timestamptz := now();
begin
  if p_review_type not in ('daily', 'weekly') then
    raise exception 'invalid_bot_ops_review_type';
  end if;
  if nullif(trim(p_schedule_key), '') is null or nullif(trim(p_owner), '') is null then
    raise exception 'invalid_bot_ops_claim';
  end if;

  insert into public.bot_ops_state (review_type) values (p_review_type)
  on conflict (review_type) do nothing;
  select * into v_state from public.bot_ops_state where review_type = p_review_type for update;
  select * into v_run from public.bot_ops_runs
    where review_type = p_review_type and schedule_key = p_schedule_key
    for update;

  if found then
    if v_run.status = 'completed' or (v_run.status = 'running' and v_run.lease_until > v_now) then
      return;
    end if;
    update public.bot_ops_runs set
      status = 'running', owner = left(p_owner, 200),
      lease_until = v_now + make_interval(secs => greatest(60, least(coalesce(p_lease_seconds, 900), 3600))),
      cursor_start = v_state.last_event_seq, cursor_end = v_state.last_event_seq,
      started_at = v_now, completed_at = null, error = null
    where id = v_run.id returning * into v_run;
  else
    insert into public.bot_ops_runs (
      review_type, schedule_key, status, owner, lease_until, cursor_start, cursor_end, started_at
    ) values (
      p_review_type, left(p_schedule_key, 80), 'running', left(p_owner, 200),
      v_now + make_interval(secs => greatest(60, least(coalesce(p_lease_seconds, 900), 3600))),
      v_state.last_event_seq, v_state.last_event_seq, v_now
    ) returning * into v_run;
  end if;

  return next v_run;
end;
$$;

create or replace function public.upsert_bot_ops_finding_v1(p_finding jsonb)
returns setof public.bot_ops_findings
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.bot_ops_findings%rowtype;
  v_occurrence_inserted integer := 0;
  v_dedupe text := left(p_finding->>'dedupe_key', 500);
  v_source text := left(coalesce(p_finding->>'source_event_id', p_finding->>'dedupe_key'), 500);
  v_occurred timestamptz := coalesce((p_finding->>'occurred_at')::timestamptz, now());
begin
  if nullif(v_dedupe, '') is null then raise exception 'bot_ops_finding_dedupe_required'; end if;

  insert into public.bot_ops_findings (
    dedupe_key, run_id, tenant_id, bot_id, channel, category, severity, status,
    title, detail, recommendation, requires_approval, conversation_key, source_event_id,
    evidence, safe_action, first_seen_at, last_seen_at
  ) values (
    v_dedupe, nullif(p_finding->>'run_id', '')::uuid, left(p_finding->>'tenant_id', 160),
    p_finding->>'bot_id', left(p_finding->>'channel', 80), left(p_finding->>'category', 120),
    p_finding->>'severity', p_finding->>'status', left(p_finding->>'title', 180),
    left(p_finding->>'detail', 1000), left(p_finding->>'recommendation', 1000),
    coalesce((p_finding->>'requires_approval')::boolean, false), nullif(left(p_finding->>'conversation_key', 80), ''),
    nullif(v_source, ''), coalesce(p_finding->'evidence', '{}'::jsonb), p_finding->'safe_action',
    v_occurred, v_occurred
  )
  on conflict (dedupe_key) do update set
    run_id = excluded.run_id,
    severity = case
      when public.bot_ops_findings.severity = 'critical' or excluded.severity = 'critical' then 'critical'
      when public.bot_ops_findings.severity = 'attention' or excluded.severity = 'attention' then 'attention'
      else 'opportunity' end,
    status = excluded.status,
    title = excluded.title,
    detail = excluded.detail,
    recommendation = excluded.recommendation,
    requires_approval = public.bot_ops_findings.requires_approval or excluded.requires_approval,
    source_event_id = excluded.source_event_id,
    evidence = public.bot_ops_findings.evidence || excluded.evidence,
    safe_action = coalesce(excluded.safe_action, public.bot_ops_findings.safe_action),
    last_seen_at = greatest(public.bot_ops_findings.last_seen_at, excluded.last_seen_at),
    resolved_at = null,
    updated_at = now()
  returning * into v_row;

  insert into public.bot_ops_finding_occurrences (dedupe_key, source_event_id, run_id, occurred_at)
  values (v_dedupe, v_source, nullif(p_finding->>'run_id', '')::uuid, v_occurred)
  on conflict (dedupe_key, source_event_id) do nothing;
  get diagnostics v_occurrence_inserted = row_count;

  if v_occurrence_inserted = 1 and v_row.occurrence_count > 0 and v_row.created_at <> v_row.updated_at then
    update public.bot_ops_findings set occurrence_count = occurrence_count + 1, updated_at = now()
      where id = v_row.id returning * into v_row;
  end if;
  return next v_row;
end;
$$;

create or replace function public.complete_bot_ops_review_v1(
  p_run_id uuid,
  p_cursor_end bigint,
  p_overall_status text,
  p_summary jsonb,
  p_counts jsonb
)
returns setof public.bot_ops_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.bot_ops_runs%rowtype;
  v_now timestamptz := now();
begin
  select * into v_run from public.bot_ops_runs where id = p_run_id for update;
  if not found or v_run.status <> 'running' then raise exception 'bot_ops_run_not_claimed'; end if;
  if p_overall_status not in ('healthy', 'attention', 'critical') then raise exception 'invalid_bot_ops_status'; end if;

  update public.bot_ops_runs set
    status = 'completed', cursor_end = greatest(cursor_start, coalesce(p_cursor_end, cursor_start)),
    overall_status = p_overall_status, summary = coalesce(p_summary, '{}'::jsonb),
    counts = coalesce(p_counts, '{}'::jsonb), completed_at = v_now, lease_until = null, error = null
  where id = p_run_id returning * into v_run;

  update public.bot_ops_state set
    last_event_seq = greatest(last_event_seq, v_run.cursor_end), last_run_id = v_run.id,
    last_completed_at = v_now, updated_at = v_now
  where review_type = v_run.review_type;

  return next v_run;
end;
$$;

revoke all on function public.bot_ops_storage_ready_v1() from public, anon, authenticated;
revoke all on function public.claim_bot_ops_review_v1(text, text, text, integer) from public, anon, authenticated;
revoke all on function public.upsert_bot_ops_finding_v1(jsonb) from public, anon, authenticated;
revoke all on function public.complete_bot_ops_review_v1(uuid, bigint, text, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.bot_ops_storage_ready_v1() to service_role;
grant execute on function public.claim_bot_ops_review_v1(text, text, text, integer) to service_role;
grant execute on function public.upsert_bot_ops_finding_v1(jsonb) to service_role;
grant execute on function public.complete_bot_ops_review_v1(uuid, bigint, text, jsonb, jsonb) to service_role;

commit;
