-- Nextfor IA · citas multi-tenant (piloto DERCO)
-- PII is stored encrypted inside payload. Operational fields remain queryable.

create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  conversation_id text not null,
  agent_id text,
  status text not null check (status in ('booked','requested','failed','cancelled','rescheduled','not_requested')),
  starts_at timestamptz,
  payload text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, conversation_id)
);

create index if not exists appointments_tenant_start_idx
  on public.appointments (tenant_id, starts_at desc);

create index if not exists appointments_tenant_status_idx
  on public.appointments (tenant_id, status, updated_at desc);

alter table public.appointments enable row level security;

-- The application uses the Supabase service role. Do not add public policies.
